"""Luxtronik number sensors definitions."""
# region Imports
from homeassistant.components.number import NumberMode
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricPotential,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.helpers.entity import EntityCategory

from .const import (
    DeviceKey,
    Calculation_SensorKey as LC,
    Parameter_Config_SensorKey as LCP,
    Parameter_SensorKey as LP,
    Visibility_SensorKey as LV,
    SensorAttrFormat,
    SensorAttrKey as SA,
)
from .model import (
    ATTR_DESCRIPTION,
    LuxtronikEntityAttributeDescription as attr,
    LuxtronikNumberDescription,
)

# endregion Imports

# TODO:
# ID_Einst_HysHzExEn_akt TEE Heizung    2 1-15
# ID_Einst_HysBwExEn_akt TEE Warmw.     5 1-15
# T-Diff. Speicher max 70 20-95
# T-Diff. Koll. max 110 90-120

NUMBER_SENSORS: list[LuxtronikNumberDescription] = [
    # region Main heatpump
    LuxtronikNumberDescription(
        luxtronik_key=LCP.RELEASE_SECOND_HEAT_GENERATOR,
        icon="mdi:download-lock",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-20.0,
        native_max_value=20.0,
        native_step=0.1,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
        factor=0.1,  # TODO: Check
        visibility=LV.SECOND_HEAT_GENERATOR,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATSOURCE_DEFROST_AIR_THRESHOLD_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=6.0,
        native_max_value=20.0,
        native_step=1.0,
        mode=NumberMode.SLIDER,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
        extra_attributes=[ATTR_DESCRIPTION],
        visibility=LV.HEATSOURCE_DEFROST_AIR_THRESHOLD_TEMPERATURE,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.AIR_DEFROST_STOP_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=2.0,
        native_max_value=10.0,
        native_step=1.0,
        mode=NumberMode.SLIDER,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
        extra_attributes=[ATTR_DESCRIPTION],
        visibility=LV.HEATSOURCE_DEFROST_AIR_END_TEMPERATURE,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.RELEASE_TIME_SECOND_HEAT_GENERATOR,
        translation_key_name="release_second_heat_generator",
        icon="mdi:timer-play",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        native_min_value=20,
        native_max_value=120,
        native_step=5,
        entity_category=EntityCategory.CONFIG,
        factor=1,  # TODO: Check
        visibility=LV.SECOND_HEAT_GENERATOR,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.EFFICIENCY_PUMP_NOMINAL,
        icon="mdi:leaf-circle-outline",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        native_min_value=3.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        factor=0.01,  # TODO: Check
        entity_registry_enabled_default=False,
        visibility=LV.EFFICIENCY_PUMP_NOMINAL,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.EFFICIENCY_PUMP_MINIMAL,
        icon="mdi:leaf",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        native_min_value=3.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        factor=0.01,  # TODO: Check
        entity_registry_enabled_default=False,
        visibility=LV.EFFICIENCY_PUMP_MINIMAL,
    ),
    # endregion Main heatpump
    # region Heating
    LuxtronikNumberDescription(
        luxtronik_key=LP.HEATING_TARGET_CORRECTION,
        device_key=DeviceKey.heating,
        icon="mdi:plus-minus-variant",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-5.0,
        native_max_value=5.0,
        native_step=0.1,
        mode=NumberMode.BOX,
        update_interval=None,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.PUMP_OPTIMIZATION_TIME,
        translation_key_name="pump_optimization",
        device_key=DeviceKey.heating,
        icon="mdi:timer-settings",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        native_min_value=5,
        native_max_value=180,
        native_step=5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=1,  # TODO: Check
        visibility=LV.PUMP_OPTIMIZATION,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_THRESHOLD_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:download-outline",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_MIN_FLOW_OUT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:waves-arrow-left",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,  # TODO: Check
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT_CURVE1_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20.0,
        native_max_value=70.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT_CURVE2_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=35.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT_CURVE_NIGHT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-15.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT2_CURVE1_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20.0,
        native_max_value=70.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK2,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT2_CURVE2_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=35.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK2,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT2_CURVE_NIGHT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-15.0,
        native_max_value=10.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK2,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT3_CURVE1_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20.0,
        native_max_value=70.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK3,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT3_CURVE2_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=35.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK3,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_CIRCUIT3_CURVE_NIGHT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-15.0,
        native_max_value=10.0,
        native_step=0.5,
        factor=0.1,  # TODO: Check
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK3,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_NIGHT_LOWERING_TO_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer-low",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-20.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,  # TODO: Check
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_RETURN_TEMPERATURE_LIMIT,
        device_key=DeviceKey.heating,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=35.0,
        native_max_value=70.0,
        native_step=1.0,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.SLIDER,
        extra_attributes=[ATTR_DESCRIPTION],
        entity_registry_enabled_default=False,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_HYSTERESIS,
        device_key=DeviceKey.heating,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=0.5,
        native_max_value=6.0,
        native_step=0.1,
        entity_category=EntityCategory.CONFIG,
        factor=0.1,  # TODO: Check
        visibility=LV.HEATING_HYSTERESIS,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_MAX_FLOW_OUT_INCREASE_TEMPERATURE,
        device_key=DeviceKey.heating,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=1.0,
        native_max_value=7.0,
        native_step=0.1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,  # TODO: Check
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_MAXIMUM_CIRCULATION_PUMP_SPEED,
        device_key=DeviceKey.heating,
        icon="mdi:speedometer",
        device_class=SensorDeviceClass.SPEED,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=100,
        native_step=10,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
    ),
    # 0% Regelung nur nach Außenemperatur
    # 100% 1K Temperaturdifferenz im Raum führt zu 1K Anpassung der Rücklauf-Solltemperatur <-- empf. Fussbodenheizung
    # 200% 1K Temperaturdifferenz im Raum führt zu 2K Anpassung der Rücklauf-Solltemperatur <-- empf. Radiatoren / Gebläsekonvektoren
    LuxtronikNumberDescription(
        luxtronik_key=LCP.HEATING_ROOM_TEMPERATURE_IMPACT_FACTOR,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer-chevron-up",
        device_class=None,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=200,
        native_step=10,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
        visibility=LV.ROOM_THERMOSTAT,
    ),
    # endregion Heating
    # region Domestic water
    LuxtronikNumberDescription(
        luxtronik_key=LP.DHW_TARGET_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        mode=NumberMode.BOX,
        icon="mdi:thermometer-water",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-40.0,
        native_max_value=60.0,
        native_step=1.0,
        update_interval=None,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.DHW_HYSTERESIS,
        device_key=DeviceKey.domestic_water,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=1.0,
        native_max_value=30.0,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_step=0.1,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.DHW_THERMAL_DESINFECTION_TARGET,
        device_key=DeviceKey.domestic_water,
        icon="mdi:thermometer-high",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=50.0,
        native_max_value=70.0,
        native_step=1.0,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,  # TODO: Check
        extra_attributes=[
            attr(
                SA.LAST_THERMAL_DESINFECTION,
                LC.DHW_TEMPERATURE,
                SensorAttrFormat.TIMESTAMP_LAST_OVER,
                True,
            ),
        ],
    ),
    # region Solar
    LuxtronikNumberDescription(
        luxtronik_key=LCP.SOLAR_PUMP_ON_DIFFERENCE_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        icon="mdi:pump",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=2.0,
        native_max_value=15.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.SOLAR,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.SOLAR_PUMP_OFF_DIFFERENCE_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        icon="mdi:pump-off",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=0.5,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.SOLAR,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.SOLAR_PUMP_OFF_MAX_DIFFERENCE_TEMPERATURE_BOILER,
        device_key=DeviceKey.domestic_water,
        icon="mdi:water-boiler-alert",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20,
        native_max_value=95,
        native_step=1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.SOLAR,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.SOLAR_PUMP_MAX_TEMPERATURE_COLLECTOR,
        device_key=DeviceKey.domestic_water,
        icon="mdi:solar-panel-large",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=90,
        native_max_value=120,
        native_step=1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.SOLAR_COLLECTOR,
    ),
    # endregion Solar
    # endregion Domestic water
    # region Cooling
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_OUTDOOR_TEMP_THRESHOLD,
        device_key=DeviceKey.cooling,
        icon="mdi:sun-thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=18.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.COOLING,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_START_DELAY_HOURS,
        device_key=DeviceKey.cooling,
        icon="mdi:clock-start",
        native_unit_of_measurement=UnitOfTime.HOURS,
        native_min_value=0.0,
        native_max_value=12.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.COOLING,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_STOP_DELAY_HOURS,
        device_key=DeviceKey.cooling,
        icon="mdi:clock-end",
        native_unit_of_measurement=UnitOfTime.HOURS,
        native_min_value=0.0,
        native_max_value=12.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.COOLING,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_TARGET_TEMPERATURE_MK1,
        device_key=DeviceKey.cooling,
        icon="mdi:sun-thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=18.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK1,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_TARGET_TEMPERATURE_MK2,
        device_key=DeviceKey.cooling,
        icon="mdi:sun-thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=18.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK2,
    ),
    LuxtronikNumberDescription(
        luxtronik_key=LCP.COOLING_TARGET_TEMPERATURE_MK3,
        device_key=DeviceKey.cooling,
        icon="mdi:sun-thermometer",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=18.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LV.MK3,
    ),
    # endregion Cooling
]

