# All descriptions can be found here.
# region Imports
from homeassistant.components.number import NumberMode
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.const import PERCENTAGE, UnitOfTemperature, UnitOfTime
from homeassistant.helpers.entity import EntityCategory

from .const import DeviceKey, LuxParameter, LuxVisibility
from .model import LuxtronikNumberDescription

# endregion Imports

# TODO:
# ID_Einst_HysHzExEn_akt TEE Heizung    2 1-15
# ID_Einst_HysBwExEn_akt TEE Warmw.     5 1-15
# T-Diff. Speicher max 70 20-95
# T-Diff. Koll. max 110 90-120

NUMBER_SENSORS: list[LuxtronikNumberDescription] = [
    # region Main heatpump
    LuxtronikNumberDescription(
        key="release_second_heat_generator",
        luxtronik_key=LuxParameter.P0090_RELEASE_SECOND_HEAT_GENERATOR,
        icon="mdi:download-lock",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-20.0,
        native_max_value=20.0,
        native_step=0.1,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
        factor=0.1,
        visibility=LuxVisibility.V0061_SECOND_HEAT_GENERATOR,
    ),
    LuxtronikNumberDescription(
        key="release_time_second_heat_generator",
        luxtronik_key=LuxParameter.P0992_RELEASE_TIME_SECOND_HEAT_GENERATOR,
        translation_key_name="release_second_heat_generator",
        icon="mdi:timer-play",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.MINUTES,
        native_min_value=20,
        native_max_value=120,
        native_step=5,
        entity_category=EntityCategory.CONFIG,
        factor=1,
        visibility=LuxVisibility.V0061_SECOND_HEAT_GENERATOR,
    ),
    # endregion Main heatpump
    # region Heating
    LuxtronikNumberDescription(
        key="heating_target_correction",
        luxtronik_key=LuxParameter.P0001_HEATING_TARGET_CORRECTION,
        device_key=DeviceKey.heating,
        icon="mdi:plus-minus-variant",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-5.0,
        native_max_value=5.0,
        native_step=0.1,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        key="pump_optimization_time",
        luxtronik_key=LuxParameter.P0864_PUMP_OPTIMIZATION_TIME,
        translation_key_name="pump_optimization",
        device_key=DeviceKey.heating,
        icon="mdi:timer-settings",
        device_class=SensorDeviceClass.DURATION,
        native_unit_of_measurement=UnitOfTime.MINUTES,
        native_min_value=5,
        native_max_value=180,
        native_step=5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=1,
        visibility=LuxVisibility.V0144_PUMP_OPTIMIZATION,
    ),
    LuxtronikNumberDescription(
        key="heating_threshold_temperature",
        luxtronik_key=LuxParameter.P0700_HEATING_THRESHOLD_TEMPERATURE,
        translation_key_name="heating_threshold",
        device_key=DeviceKey.heating,
        icon="mdi:download-outline",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        key="heating_min_flow_out_temperature",
        luxtronik_key=LuxParameter.P0979_HEATING_MIN_FLOW_OUT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:waves-arrow-left",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=30.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,
    ),
    LuxtronikNumberDescription(
        key="heating_circuit_curve1_temperature",
        luxtronik_key=LuxParameter.P0011_HEATING_CIRCUIT_CURVE1_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20.0,
        native_max_value=70.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        key="heating_circuit_curve2_temperature",
        luxtronik_key=LuxParameter.P0012_HEATING_CIRCUIT_CURVE2_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=5.0,
        native_max_value=35.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        key="heating_circuit_curve_night_temperature",
        luxtronik_key=LuxParameter.P0013_HEATING_CIRCUIT_CURVE_NIGHT_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:chart-bell-curve",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-15.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
    ),
    LuxtronikNumberDescription(
        key="heating_night_lowering_to_temperature",
        luxtronik_key=LuxParameter.P0111_HEATING_NIGHT_LOWERING_TO_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer-low",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-20.0,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,
    ),
    LuxtronikNumberDescription(
        key="heating_hysteresis",
        luxtronik_key=LuxParameter.P0088_HEATING_HYSTERESIS,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=0.5,
        native_max_value=6.0,
        native_step=0.1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,
    ),
    LuxtronikNumberDescription(
        key="heating_max_flow_out_increase_temperature",
        luxtronik_key=LuxParameter.P0089_HEATING_MAX_FLOW_OUT_INCREASE_TEMPERATURE,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=1.0,
        native_max_value=7.0,
        native_step=0.1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,
    ),
    LuxtronikNumberDescription(
        key="heating_maximum_circulation_pump_speed",
        luxtronik_key=LuxParameter.P1032_HEATING_MAXIMUM_CIRCULATION_PUMP_SPEED,
        device_key=DeviceKey.heating,
        icon="mdi:speedometer",
        device_class=SensorDeviceClass.SPEED,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=100,
        native_step=10,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
    ),
    # 0% Regelung nur nach Außenemperatur
    # 100% 1K Temperaturdifferenz im Raum führt zu 1K Anpassung der Rücklauf-Solltemperatur <-- empf. Fussbodenheizung
    # 200% 1K Temperaturdifferenz im Raum führt zu 2K Anpassung der Rücklauf-Solltemperatur <-- empf. Radiatoren / Gebläsekonvektoren
    LuxtronikNumberDescription(
        key="heating_room_temperature_impact_factor",
        luxtronik_key=LuxParameter.P0980_HEATING_ROOM_TEMPERATURE_IMPACT_FACTOR,
        device_key=DeviceKey.heating,
        icon="mdi:thermometer-chevron-up",
        device_class=None,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=200,
        native_step=10,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
        entity_registry_enabled_default=False,
        visibility=LuxVisibility.V0122_ROOM_THERMOSTAT,
    ),
    # endregion Heating
    # region Domestic water
    LuxtronikNumberDescription(
        key="domestic_water_target_temperature",
        luxtronik_key=LuxParameter.P0002_DOMESTIC_WATER_TARGET_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        mode=NumberMode.BOX,
        icon="mdi:thermometer-water",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=-40.0,
        native_max_value=60.0,
        native_step=1.0,
    ),
    LuxtronikNumberDescription(
        key="domestic_water_hysteresis",
        luxtronik_key=LuxParameter.P0074_DOMESTIC_WATER_HYSTERESIS,
        device_key=DeviceKey.domestic_water,
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=1.0,
        native_max_value=30.0,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        native_step=0.1,
    ),
    LuxtronikNumberDescription(
        key="domestic_water_thermal_desinfection_target",
        luxtronik_key=LuxParameter.P0047_DOMESTIC_WATER_THERMAL_DESINFECTION_TARGET,
        device_key=DeviceKey.domestic_water,
        icon="mdi:thermometer-high",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=50.0,
        native_max_value=70.0,
        native_step=1.0,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        factor=0.1,
    ),
    # region Solar
    LuxtronikNumberDescription(
        key="solar_pump_on_difference_temperature",
        luxtronik_key=LuxParameter.P0122_SOLAR_PUMP_ON_DIFFERENCE_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        icon="mdi:pump",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=2.0,
        native_max_value=15.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LuxVisibility.V0250_SOLAR,
    ),
    LuxtronikNumberDescription(
        key="solar_pump_off_difference_temperature",
        luxtronik_key=LuxParameter.P0123_SOLAR_PUMP_OFF_DIFFERENCE_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        icon="mdi:pump-off",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        native_min_value=0.5,
        native_max_value=10.0,
        native_step=0.5,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LuxVisibility.V0250_SOLAR,
    ),
    LuxtronikNumberDescription(
        key="solar_pump_off_max_difference_temperature_boiler",
        luxtronik_key=LuxParameter.P0289_SOLAR_PUMP_OFF_MAX_DIFFERENCE_TEMPERATURE_BOILER,
        device_key=DeviceKey.domestic_water,
        icon="mdi:water-boiler-alert",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=20,
        native_max_value=95,
        native_step=1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LuxVisibility.V0250_SOLAR,
    ),
    LuxtronikNumberDescription(
        key="solar_pump_max_temperature_collector",
        luxtronik_key=LuxParameter.P0883_SOLAR_PUMP_MAX_TEMPERATURE_COLLECTOR,
        device_key=DeviceKey.domestic_water,
        icon="mdi:solar-panel-large",
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        native_min_value=90,
        native_max_value=120,
        native_step=1,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        visibility=LuxVisibility.V0038_SOLAR_COLLECTOR,
        value_none_existing=5.0,
    ),
    # endregion Solar
    # endregion Domestic water
    # region Cooling
    # LuxtronikNumberDescription(
    #     device_key=DeviceKey.cooling,
    #     luxtronik_key=LuxParameter.P0108_MODE_COOLING,
    #     key="cooling",
    #     icon="mdi:snowflake",
    #     entity_category=EntityCategory.CONFIG,
    #     device_class=None,
    #     on_state=LuxMode.automatic.value,
    #     off_state=LuxMode.off.value,
    # ),
    # endregion Cooling
]
