"""Luxtronik sensors definitions."""
# region Imports
from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfPressure,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.helpers.entity import EntityCategory

from .const import (
    LUX_STATE_ICON_MAP,
    SECOUND_TO_HOUR_FACTOR,
    UPDATE_INTERVAL_NORMAL,
    UPDATE_INTERVAL_SLOW,
    UPDATE_INTERVAL_VERY_SLOW,
    DeviceKey,
    FirmwareVersionMinor,
    Calculation_SensorKey as LC,
    LuxOperationMode,
    Parameter_All_SensorKey as LPA,
    LuxStatus1Option,
    LuxStatus3Option,
    LuxSwitchoffReason,
    Visibility_SensorKey as LV,
    SensorAttrFormat,
    SensorAttrKey as SA,
    UnitOfVolumeFlowRateExt,
)
from .model import (
    ATTR_DESCRIPTION,
    LuxtronikEntityAttributeDescription as attr,
    LuxtronikSensorDescription as descr,
    LuxtronikIndexSensorDescription as descr_index,
    LuxtronikPeriodStatSensorDescription as descr_period,
)

# endregion Imports

SENSORS_STATUS: list[descr] = [
    descr(
        luxtronik_key=LC.STATUS,
        icon_by_state=LUX_STATE_ICON_MAP,
        device_class=SensorDeviceClass.ENUM,
        extra_attributes=[
            ATTR_DESCRIPTION,
            attr(SA.EVU_FIRST_START_TIME, LC.UNSET, None, True),
            attr(SA.EVU_FIRST_END_TIME, LC.UNSET, None, True),
            attr(SA.EVU_SECOND_START_TIME, LC.UNSET, None, True),
            attr(SA.EVU_SECOND_END_TIME, LC.UNSET, None, True),
        ],
        options=[e.value for e in LuxOperationMode],
        update_interval=UPDATE_INTERVAL_NORMAL,
    ),
]

SENSORS_INDEX: list[descr_index] = [
    descr_index(
        luxtronik_key=LPA.SWITCHOFF_REASON,
        luxtronik_key_timestamp=LPA.SWITCHOFF_TIMESTAMP,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:electric-switch",
        device_class=SensorDeviceClass.ENUM,
        options=[e.value for e in LuxSwitchoffReason],
    ),
]

SENSORS_PERIOD: list[descr_period] = [
    descr_period(
        luxtronik_key=LC.COMPRESSOR1_IMPULSES,
        icon="mdi:pulse",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement="\u2211",
        entity_registry_enabled_default=False,
        visibility=LV.COMPRESSOR1_IMPULSES,
    ),
    descr_period(
        luxtronik_key=LC.STATUS_TIME,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sand",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        entity_registry_visible_default=False,
        native_precision=0,
        extra_attributes=[
            attr(SA.STATUS_TEXT, LC.STATUS_TIME, SensorAttrFormat.HOUR_MINUTE),
            attr(SA.TIMER_HEATPUMP_ON, LC.TIMER_HEATPUMP_ON),
            attr(SA.TIMER_ADD_HEAT_GENERATOR_ON, LC.TIMER_ADD_HEAT_GENERATOR_ON),
            attr(SA.TIMER_SEC_HEAT_GENERATOR_ON, LC.TIMER_SEC_HEAT_GENERATOR_ON),
            attr(SA.TIMER_NET_INPUT_DELAY, LC.TIMER_NET_INPUT_DELAY),
            attr(SA.TIMER_SCB_OFF, LC.TIMER_SCB_OFF),
            attr(SA.TIMER_SCB_ON, LC.TIMER_SCB_ON),
            attr(SA.TIMER_COMPRESSOR_OFF, LC.TIMER_COMPRESSOR_OFF),
            attr(SA.TIMER_HC_ADD, LC.TIMER_HC_ADD),
            attr(SA.TIMER_HC_LESS, LC.TIMER_HC_LESS),
            attr(SA.TIMER_TDI, LC.TIMER_TDI),
            attr(SA.TIMER_BLOCK_DHW, LC.TIMER_BLOCK_DHW),
            attr(SA.TIMER_DEFROST, LC.TIMER_DEFROST),
            attr(SA.TIMER_HOT_GAS, LC.TIMER_HOT_GAS),
        ],
    ),
]

SENSORS: list[descr] = [
    # region Main heatpump
    # descr(
    #     luxtronik_key=LC.STATUS_TIME,
    #     entity_category=EntityCategory.DIAGNOSTIC,
    #     icon="mdi:timer-sand",
    #     native_unit_of_measurement=UnitOfTime.SECONDS,
    #     entity_registry_visible_default=False,
    #     native_precision=0,
    #     extra_attributes=[
    #         attr(SA.STATUS_TEXT, LC.STATUS_TIME, SensorAttrFormat.HOUR_MINUTE),
    #         attr(SA.TIMER_HEATPUMP_ON, LC.TIMER_HEATPUMP_ON),
    #         attr(SA.TIMER_ADD_HEAT_GENERATOR_ON, LC.TIMER_ADD_HEAT_GENERATOR_ON),
    #         attr(SA.TIMER_SEC_HEAT_GENERATOR_ON, LC.TIMER_SEC_HEAT_GENERATOR_ON),
    #         attr(SA.TIMER_NET_INPUT_DELAY, LC.TIMER_NET_INPUT_DELAY),
    #         attr(SA.TIMER_SCB_OFF, LC.TIMER_SCB_OFF),
    #         attr(SA.TIMER_SCB_ON, LC.TIMER_SCB_ON),
    #         attr(SA.TIMER_COMPRESSOR_OFF, LC.TIMER_COMPRESSOR_OFF),
    #         attr(SA.TIMER_HC_ADD, LC.TIMER_HC_ADD),
    #         attr(SA.TIMER_HC_LESS, LC.TIMER_HC_LESS),
    #         attr(SA.TIMER_TDI, LC.TIMER_TDI),
    #         attr(SA.TIMER_BLOCK_DHW, LC.TIMER_BLOCK_DHW),
    #         attr(SA.TIMER_DEFROST, LC.TIMER_DEFROST),
    #         attr(SA.TIMER_HOT_GAS, LC.TIMER_HOT_GAS),
    #     ],
    # ),
    descr(
        luxtronik_key=LC.STATUS_LINE_1,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:numeric-1-circle",
        entity_registry_visible_default=False,
        device_class=SensorDeviceClass.ENUM,
        options=[e.value for e in LuxStatus1Option]
        # translation_key="status1",
    ),
    descr(
        luxtronik_key=LC.STATUS_LINE_2,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:numeric-2-circle",
        entity_registry_visible_default=False,
        device_class=SensorDeviceClass.ENUM,
        options=["since", "in"],
        # translation_key="status2",
    ),
    descr(
        luxtronik_key=LC.STATUS_LINE_3,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:numeric-3-circle",
        entity_registry_visible_default=False,
        device_class=SensorDeviceClass.ENUM,
        options=[e.value for e in LuxStatus3Option],
        # translation_key="status3",
    ),
    descr(
        luxtronik_key=LC.HEAT_SOURCE_INPUT_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        update_interval=UPDATE_INTERVAL_NORMAL,
    ),
    descr(
        luxtronik_key=LC.OUTDOOR_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        update_interval=UPDATE_INTERVAL_SLOW,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    descr(
        luxtronik_key=LC.OUTDOOR_TEMPERATURE_AVERAGE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.COMPRESSOR1_OPERATION_HOURS,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        visibility=LV.COMPRESSOR1_OPERATION_HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.COMPRESSOR2_IMPULSES,
        icon="mdi:pulse",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement="\u2211",
        entity_registry_enabled_default=False,
        visibility=LV.COMPRESSOR2_IMPULSES,
    ),
    descr(
        luxtronik_key=LC.COMPRESSOR2_OPERATION_HOURS,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        visibility=LV.COMPRESSOR2_OPERATION_HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.OPERATION_HOURS,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.HEAT_AMOUNT_COUNTER,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        native_precision=1,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.HEAT_AMOUNT_FLOW_RATE,
        device_key=DeviceKey.heating,
        icon="mdi:water-sync",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,  # SensorDeviceClass.WATER, <- There is no predefined device class for flow at the moment.
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfVolumeFlowRateExt.LITER_PER_HOUR,
        native_precision=1,
        update_interval=UPDATE_INTERVAL_NORMAL,
    ),
    descr(
        luxtronik_key=LC.HEAT_SOURCE_FLOW_RATE,
        device_key=DeviceKey.heating,
        icon="mdi:water-sync",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,  # SensorDeviceClass.WATER, <- There is no predefined device class for flow at the moment.
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfVolumeFlowRateExt.LITER_PER_HOUR,
        native_precision=1,
        update_interval=UPDATE_INTERVAL_NORMAL,
    ),
    descr(
        luxtronik_key=LC.HOT_GAS_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.HOT_GAS_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.SUCTION_COMPRESSOR_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.SUCTION_COMPRESSOR_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.SUCTION_EVAPORATOR_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.SUCTION_EVAPORATOR_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.COMPRESSOR_HEATING_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.COMPRESSOR_HEATING,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    descr(
        luxtronik_key=LC.OVERHEATING_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        visibility=LV.OVERHEATING_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.OVERHEATING_TARGET_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        visibility=LV.OVERHEATING_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.HIGH_PRESSURE,
        icon="mdi:gauge-full",
        native_unit_of_measurement=UnitOfPressure.BAR,
        visibility=LV.LIN_PRESSURE,
    ),
    descr(
        luxtronik_key=LC.LOW_PRESSURE,
        icon="mdi:gauge-low",
        native_unit_of_measurement=UnitOfPressure.BAR,
        visibility=LV.LIN_PRESSURE,
    ),
    descr(
        luxtronik_key=LC.ADDITIONAL_HEAT_GENERATOR_OPERATION_HOURS,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        visibility=LV.ADDITIONAL_HEAT_GENERATOR_OPERATION_HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LPA.ADDITIONAL_HEAT_GENERATOR_AMOUNT_COUNTER,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        invisible_if_value=0.0,
        visibility=LV.ADDITIONAL_HEAT_GENERATOR_AMOUNT_COUNTER,
        factor=0.1,  # TODO: Check
        native_precision=1,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.ANALOG_OUT1,
        icon="mdi:alpha-v-circle-outline",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        visibility=LV.ANALOG_OUT1,
        entity_registry_enabled_default=False,
        factor=0.1,  # TODO!: Check
    ),
    descr(
        luxtronik_key=LC.ANALOG_OUT2,
        icon="mdi:alpha-v-circle-outline",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        visibility=LV.ANALOG_OUT2,
        entity_registry_enabled_default=False,
        factor=0.1,  # TODO: Check
    ),
    descr(
        luxtronik_key=LC.CURRENT_HEAT_OUTPUT,
        icon="mdi:lightning-bolt-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfPower.WATT,
        entity_registry_enabled_default=False,
        native_precision=0,
    ),
    descr(
        luxtronik_key=LC.PUMP_FREQUENCY,
        icon="mdi:sine-wave",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        entity_registry_enabled_default=False,
    ),
    descr(
        luxtronik_key=LC.PUMP_FLOW_DELTA_TARGET,
        icon="mdi:delta",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        factor=0.1,  # TODO: Check
        entity_registry_enabled_default=False,
    ),
    descr(
        luxtronik_key=LC.PUMP_FLOW_DELTA,
        icon="mdi:delta",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        factor=0.1,  # TODO: Check
        entity_registry_enabled_default=False,
    ),
    descr(
        luxtronik_key=LC.CIRCULATION_PUMP_DELTA_TARGET,
        icon="mdi:delta",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        factor=0.1,  # TODO: Check
        entity_registry_enabled_default=False,
    ),
    descr(
        luxtronik_key=LC.CIRCULATION_PUMP_DELTA,
        icon="mdi:delta",
        native_unit_of_measurement=UnitOfTemperature.KELVIN,
        factor=0.1,  # TODO: Check
        entity_registry_enabled_default=False,
    ),
    descr(
        luxtronik_key=LC.HEAT_SOURCE_OUTPUT_TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        entity_registry_enabled_default=False,
        invisible_if_value=-50.0,
        visibility=LV.OVERHEATING_TEMPERATURE,
    ),
    descr(
        luxtronik_key=LC.ERROR_REASON,
        icon="mdi:alert",
        extra_attributes=[
            attr(SA.TIMESTAMP, LC.ERROR_TIME),
            attr(SA.CODE, LC.ERROR_REASON),
            attr(SA.CAUSE, LC.ERROR_REASON),
            attr(SA.REMEDY, LC.ERROR_REASON),
        ],
    ),
    descr(
        luxtronik_key=LPA.LAST_DEFROST_TIMESTAMP,
        icon="mdi:car-defrost-rear",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
        # TODO: Extend with Duration, Ambient- + Air-In-Temperatures, at the Start and end attributes of defrost!
        # extra_attributes=[
        #     attr(
        #         SA.DURATION,
        #         format=SensorAttrFormat.DURATION,
        #     ),
        #     attr(
        #         SA.AMBIENT_TEMPERATURE,
        #         LC.OUTDOOR_TEMPERATURE,
        #     ),
        #     attr(
        #         SA.HEAT_SOURCE_INPUT_TEMPERATURE,
        #         LC.HEAT_SOURCE_INPUT_TEMPERATURE,
        #     ),
        # ],
    ),

    # endregion Main heatpump
    # region Heating
    descr(
        luxtronik_key=LC.FLOW_IN_TEMPERATURE,
        device_key=DeviceKey.heating,
        entity_category=None,
        icon="mdi:waves-arrow-right",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        extra_attributes=[
            attr(
                SA.MAX_ALLOWED,
                LPA.FLOW_IN_TEMPERATURE_MAX_ALLOWED,
                SensorAttrFormat.CELSIUS_TENTH,
            ),
        ],
    ),
    descr(
        luxtronik_key=LC.FLOW_OUT_TEMPERATURE,
        device_key=DeviceKey.heating,
        entity_category=None,
        icon="mdi:waves-arrow-left",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    descr(
        luxtronik_key=LC.FLOW_OUT_TEMPERATURE_TARGET,
        device_key=DeviceKey.heating,
        entity_category=None,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        extra_attributes=[
            attr(
                SA.SWITCH_GAP,
                LC.FLOW_OUT_TEMPERATURE,
                SensorAttrFormat.SWITCH_GAP,
            ),
        ],
    ),
    descr(
        luxtronik_key=LC.OPERATION_HOURS_HEATING,
        device_key=DeviceKey.heating,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.HEAT_AMOUNT_HEATING,
        device_key=DeviceKey.heating,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        native_precision=1,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LPA.HEAT_ENERGY_INPUT,
        device_key=DeviceKey.heating,
        icon="mdi:circle-slice-3",
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        native_precision=2,
        factor=0.01,  # TODO: Check!
        min_firmware_version_minor=FirmwareVersionMinor.minor_88,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.FLOW_OUT_TEMPERATURE_EXTERNAL,
        device_key=DeviceKey.heating,
        entity_category=None,
        icon="mdi:waves-arrow-right",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.FLOW_OUT_TEMPERATURE_EXTERNAL,
    ),
    descr(
        luxtronik_key=LC.ROOM_THERMOSTAT_TEMPERATURE,
        device_key=DeviceKey.heating,
        entity_category=None,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.ROOM_THERMOSTAT,
    ),
    descr(
        luxtronik_key=LC.ROOM_THERMOSTAT_TEMPERATURE_TARGET,
        device_key=DeviceKey.heating,
        entity_category=None,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.ROOM_THERMOSTAT,
    ),
    # endregion Heating
    # region Domestic water
    descr(
        luxtronik_key=LC.DHW_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        entity_category=None,
        icon="mdi:coolant-temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    descr(
        luxtronik_key=LC.DHW_OPERATION_HOURS,
        device_key=DeviceKey.domestic_water,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement=UnitOfTime.HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.DHW_HEAT_AMOUNT,
        device_key=DeviceKey.domestic_water,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        native_precision=1,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LPA.DHW_ENERGY_INPUT,
        device_key=DeviceKey.domestic_water,
        icon="mdi:circle-slice-3",
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        native_precision=2,
        factor=0.01,  # TODO!: Check
        min_firmware_version_minor=FirmwareVersionMinor.minor_88,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    descr(
        luxtronik_key=LC.SOLAR_COLLECTOR_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        entity_category=None,
        icon="mdi:solar-panel-large",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.SOLAR_COLLECTOR,
    ),
    descr(
        luxtronik_key=LC.SOLAR_BUFFER_TEMPERATURE,
        device_key=DeviceKey.domestic_water,
        entity_category=None,
        icon="mdi:propane-tank-outline",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        visibility=LV.SOLAR_BUFFER,
    ),
    descr(
        luxtronik_key=LPA.SOLAR_OPERATION_HOURS,
        device_key=DeviceKey.domestic_water,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        visibility=LV.SOLAR_COLLECTOR,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    # endregion Domestic water
    # region Cooling
    descr(
        luxtronik_key=LC.OPERATION_HOURS_COOLING,
        device_key=DeviceKey.cooling,
        icon="mdi:timer-sand",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        native_unit_of_measurement=UnitOfTime.HOURS,
        factor=SECOUND_TO_HOUR_FACTOR,
        native_precision=2,
        update_interval=UPDATE_INTERVAL_VERY_SLOW,
    ),
    # endregion Cooling
]
