write:
  name: Write Luxtronik Parameter
  description: |
    Write a parameter to the Luxtronik heatpump.

    Example usage in YAML:

      service: luxtronik2.write
      data:
        parameter: "ID_Ba_Bw_akt"
        value: "Automatic"

  fields:
    parameter:
      name: Parameter ID
      description: The ID of the parameter to write.
      required: true
      example: "ID_Ba_Bw_akt"
      selector:
        text:
    value:
      name: Value
      description: The value to write to the parameter.
      required: true
      example: "Automatic"
      selector:
        text:
