name: Validate with hassfest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v6"
      - name: Validate with hassfest
        uses: "home-assistant/actions/hassfest@master"
