name: Linter

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Ruff
        run: pip install --upgrade ruff

      - name: Ruff format check
        run: ruff format --check custom_components/luxtronik tests

      - name: Ruff lint check
        run: ruff check custom_components/luxtronik tests

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install codespell
        run: pip install --upgrade codespell

      - name: Run codespell
        run: codespell custom_components/luxtronik tests
