# This workflow executes several linters 
# disable email notifications in your settings: 
# https://github.com/settings/notifications
name: Linter

# consider applying to all branches to help people find issues sooner
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  run-ruff-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ruff setup
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version" # skips check. setup only
      - run: ruff format # auto format
      - run: ruff check --fix # auto-fix
      
  run-ruff-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v3
        
# This pylint configuration works but has too many issues to run repeatedly.
# It should be run on-demand or scheduled until most issues are fixed.
#  run-pylint:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install pylint homeassistant luxtronik==0.3.14 requests>=2.28.2 getmac==0.8.2
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: pylint
#        run: |
#          pylint $(git ls-files '*.py')
        
  run-codespell:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
        #  skip: ./custom_components/luxtronik/translations/ 
          skip: cs.json,de.json,nl.json,pl.json
          ignore_words_list: hass

