# This workflow executes several linters 
# disable email notifications in your settings: 
# https://github.com/settings/notifications
name: Linter

# Ruff and PyLint appear to be the most commonly used linters for home assistant.
# consider applying to all branches on pre-commit to help people find issues sooner

on:
  push:
    branches: 
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  # Ruff format is a comprehensive formatting
  run-ruff:
    name: Ruff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Ruff setup
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version" # replace default "check" to do setup only.
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # optional to reduce api calls
      - name: Ruff auto format
        run: ruff format # auto format
      - name: Ruff auto fix  
        run: ruff check --fix-only # auto-fix
      - name: Commit changes # auto commit format changes.
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: format code with ruff"
      - name: Ruff check # report remaining issues
        uses: astral-sh/ruff-action@v3

# This pylint configuration works but has too many issues to run repeatedly.
# It should be run on-demand or scheduled until most issues are fixed.
#  run-pylint:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v5
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install pylint homeassistant luxtronik==0.3.14 requests>=2.28.2 getmac==0.8.2
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: pylint
#        run: |
#          pylint $(git ls-files '*.py')

  # CodeSpell performs a spellcheck. English only.      
  run-codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: CodeSpell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: cs.json,de.json,nl.json,pl.json # skip these files
          ignore_words_list: hass # skip these words
