# This workflow executes several linters 
# disable email notifications in your settings: 
# https://github.com/settings/notifications
name: Linter

# Ruff is a commonly used and fast linter for home assistant.
on:
  push:
    branches: 
      - "main"
  pull_request:
  workflow_dispatch:

# Allow Ruff to apply fixes
permissions:
  contents: write

jobs:
  # Ruff format is a comprehensive formatting
  run-ruff:
    name: Ruff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      
      - name: Ruff setup
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          #args: "--version" # replace default "check" to do setup only.
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # optional to reduce api calls
      - name: Ruff auto format
        run: ruff format # auto format
      - name: Ruff auto fix  
        run: ruff check --fix-only # auto-fix
        
      - name: Commit changes # auto commit format changes.
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Chore: format code with ruff"
      
      - name: Ruff check # report remaining issues
        uses: astral-sh/ruff-action@v3

  # CodeSpell performs a spellcheck. English only.      
  run-codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # complete all jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: CodeSpell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: cs.json,de.json,nl.json,pl.json # skip these files
          ignore_words_list: hass # skip these words
