# This workflow executes several linters 
# disable email notifications in your settings: 
# https://github.com/settings/notifications
name: Linter

on: [push, pull_request]

jobs:
  run-ruff:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ruff
        uses: astral-sh/ruff-action@v3
        
  run-pylint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: pylint
        uses: kgpl/gh-pylint@v1
        with: 
          python-version: 3.13
        
  run-codespell:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
        #  path: src
        #  skip: ./custom_components/luxtronik/translations/ 
          skip: "*cs.json, *de.json, *nl.json, *pl.json"
          ignore_words_list: hass

