# This workflow executes several linters 
# disable email notifications in your settings: 
# https://github.com/settings/notifications
name: Linter

on: [push, pull_request]

jobs:
  run-linters:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ruff
        uses: astral-sh/ruff-action@v3
        continue-on-error: true
      - name: pylint
        uses: kgpl/gh-pylint@v1
        with: 
          python-version: 3.13
        continue-on-error: true
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        continue-on-error: true
