name: Type Check

on:
  push:
    branches:
      - "main"
    paths:
      - "custom_components/luxtronik/**"
      - ".github/workflows/typecheck.yml"
      - "pyrightconfig.json"
  pull_request:
    paths:
      - "custom_components/luxtronik/**"
      - ".github/workflows/typecheck.yml"
      - "pyrightconfig.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  basedpyright:
    name: BasedPyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install basedpyright homeassistant-stubs
          pip install luxtronik==0.3.14 getmac~=0.9.0 packaging>=24.2

      - name: Run BasedPyright
        run: basedpyright custom_components/luxtronik
